[site]
bucket = "./"

[build]
command = ""

[build.processing]
skip_processing = false

[build.processing.html]
pretty_urls = true

[build.processing.css]
bundle = false
minify = false

[build.processing.js]
bundle = false
minify = false

[build.processing.images]
compress = true 